### ISSUE TITLE
Úvodní web - seznam časopisů

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/K5Journals#1]
Potřebovali bychom pro úvodní web udělat anglickou verzi:
https://journals.lib.cas.cz/magazines/seznam-casopisu
je to na enhancement

**Comment by pkudela** [comment]
Dobry den @krizovj , toto je uz hotove, prosim o otestovani na testovacim serveru -> https://k5journals.inovatika.dev/magazines/casopisy. V horni navigaci uplne vpravo je prepinani jazyku. Preklady si pak budete moct pripadne doupravit v konfiguracnich souborech.

**Comment by krizovj** [comment]
A bude možné tam dát také anglickou verzi těch textů o časopisech ("Zobrazit detail")?

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/144563327-d4e23e91-c1c1-4274-952a-05f20974055d.png)

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/144563390-cc2fca74-7bb3-4c7b-a165-ba659c40b1d7.png)

**Comment by kerschfilip** [comment]
anglická verze je OK, prosím ale upravit text v záhlaví - v angličtině by to nemělo být "Digital Library of the AV ČR" ale spíš "Digital Library of the Czech Academy of Sciences" případně "Digital Library of the CAS"

**Comment by kerschfilip** [comment]
super, díky!
