### ISSUE TITLE
Změna hesla - k7journals

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#104]
Při pokusu o změnu hesla uživatele v administraci celé aplikace i v administraci jednotlivých časopisů dochází na k7journals k chybě. Na k5journals to ale funguje normálně.

postup:
- založím nového uživatele
- kliknu na resetovat heslo a vyplním nové heslo
- aplikace mě odhlásí (v případě, že to zkouším přímo z webu konkrétního časopisu vyskočí okno s textem "not logged in"
- nově nastavené heslo nefunguje

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
funguje, děkuju!
