### ISSUE TITLE
Tučný text ve firefoxu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#106]
V informacích o článku je tučný text při prohlížení přes firefox těžko čitelný, v chromu je to OK. Šlo by to prosím upravit, třeba že by se trochu ubralo `font-weight`?

![image](https://user-images.githubusercontent.com/57805328/215508610-f5111299-269e-4c95-9076-f97510769fb2.png)

Díky

**Comment by pkudela** [comment]
ahoj @kerschfilip, je toto pozadovane chovani? Vyresil jsem to globalne pro vsechny label elementy s class "app-font-roboto-cb", to totiz delalo ten problem, ze element label ma uz definovanou vlastnost font-weight a to jeste znasobuje prirazena class s Roboto tucnym pismemem a to delalo ve Firefoxu tu neplechu, Chrome to nejak asi neresi.

Chrome
<img width="856" alt="image" src="https://user-images.githubusercontent.com/16591052/218059177-c70f1aa6-a73b-4136-86cc-d77f3db6441d.png">


Firefox
<img width="903" alt="image" src="https://user-images.githubusercontent.com/16591052/218059084-9fabb628-c131-48f1-81d2-23bbb5cc9319.png">

**Comment by pkudela** [comment]
nasazeno na serveru, prosim otestuj

**Comment by kerschfilip** [comment]
skvělý, mockrát děkuju!
