### ISSUE TITLE
Drobečková navigace u nově vytvořených položek v menu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#109]
V návaznosti na #32 jsem si všiml ještě drobného nedostatku - u nově vytvořených položek se v drobečkové navigaci neukazuje název stránky úplně hezky, viz screenshot. Šlo by to prosím nějak upravit?

![image](https://user-images.githubusercontent.com/57805328/218521204-18a2d73b-4d5c-4338-b1af-e4827590fc2b.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
super děkuju!
