### ISSUE TITLE
Náhled tisku - Mozilla

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/K5Journals#11]
V Mozille se zobrazuje náhled tisku tak, že ten náhled není vidět. Šlo by s tím něco udělat? V Chrome i v Opeře se zobrazí náhled celé stránky, ale v Mozille je jen takové úzké okno, kde není pomalu nic vidět a ani se v tom okně nejde posunout...
![tiskmozilla](https://user-images.githubusercontent.com/21309201/68104949-4b88e100-fedd-11e9-9e3f-cad41cb43261.jpg)

Šlo by to udělat tak, aby buď ten náhled byl celý nebo aby se nezobrazil vůbec?

**Comment by krizovj** [comment]
Takhle to vypadá v Chromu (a v Opeře vlastně úplně stejně):
![chrometisk](https://user-images.githubusercontent.com/21309201/68105139-e97cab80-fedd-11e9-8b9f-dcb7eb2d0ecb.jpg)

**Comment by albertoh** [comment]
Zvetsena vyska okna tisku

**Comment by krizovj** [comment]
Takhle to aspoň mně osobně přijde mnohem lepší. Ale ještě k tomu mám dotaz. Nemůžu posunout ten náhled dolů, abych viděla jeho kompletní obsah. Ptž je aktivní to přední okno s nastaveními tisku. A pokud ho zruším (Storno), tak se zavře i ten náhled. Jde s tím něco udělat nebo je to prostě vlastnost Mozilly?
![image](https://user-images.githubusercontent.com/21309201/69855467-ddd99600-128b-11ea-9309-108091d14a79.png)

**Comment by albertoh** [comment]
Bohuzel. To je systemove chovani Mozilly

**Comment by krizovj** [comment]
Jasný, chápu. Zkusím jim to vysvětlit :)
