### ISSUE TITLE
Řazení čísel a příloh

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#110]
Zdravím,

při testování před vydáním releasu jsem zkusil založit testovací časopis Slovo a slovesnost, který teď s redakcí připravujeme, a narazil jsem na to, že v Archivu se ročníky řadí správně od nejstaršího po nejnovější (viz #35), ale v rámci jednotlivých čísel to neplatí a přebírá se asi pořadí objektů z jádra Krameria.

Indexoval jsem například ročník 2021 z našeho testovacího K7 a seřadil se mi takhle:
![image](https://user-images.githubusercontent.com/57805328/218525323-61a77cc9-11a8-4c7d-bfb4-5e3f1cd4f2b9.png)

Šlo by řadit i čísla a přílohy tak, jak to dělá webový klient Krameria? tedy vzestupně podle čísla a ne podle toho, jak je to seřazené v jádře. Problém je to i proto, že v K7 zatím není implementovaný editor částí, takže čísla není možné ručně přerovnat... 

Na screenshotu je taky vidět, že se k příloze se nepřevzal žádný název, přebírají se jen názvy čísel. V Krameriovi se přitom správně ukazuje "Obsah ročníku"
![image](https://user-images.githubusercontent.com/57805328/218525412-7868e268-8654-426a-8f98-654019b66fbf.png)

Děkuju, víc už toho zakládat nebudu :-)

**Comment by kerschfilip** [comment]
problém s přebíráním toho názvu asi je, že aplikace nejspíš nepočítá s tím, když je v MODSu vyplněné `partName`. U ročníku 2016 se totiž nevytvoří název ani pro 4. číslo, které má v metadatech jak `partNumber`, tak `partName`
![image](https://user-images.githubusercontent.com/57805328/219336745-c939f6b9-1013-4581-8ae4-1bb863a00122.png)

@albertoh mohl bys ses na to prosím podívat? Potřeboval bych to nasadit u nás. Děkuju!

**Comment by albertoh** [comment]
Opraveno.
Aplikace totiz nikdy nepocitala s prilohami.

**Comment by kerschfilip** [comment]
Moc děkuju, řazení v ročníku funguje a názvy příloh se tam taky zobrazují.

Po rozkliknutí obsahu nějakého čísla z archivu se mi ale ještě vlevo zobrazuje nabídka dalších čísel a tam název přílohy chybí - šlo by ho nějak doplnit, nebo alespoň krátkou část, která se tam vejde?
![image](https://user-images.githubusercontent.com/57805328/220192313-819bf5d4-bcca-4759-b1f4-245da96ac52b.png)

A je možné, že o když řazení čísel uvnitř ročníku funguje správně, tak že aktuální číslo se pořád vyhodnocuje podle pořadí v jádru? Na hlavní stránce mi to pořád hlásí, že aktuální číslo je číslo 3, i když jsou tam přidaná i novější (zkusil jsem ho i smazat a přidat znovu, ale nepomohlo to). 

![image](https://user-images.githubusercontent.com/57805328/220192353-fd33e8f8-039e-4d0a-b61f-998d8fa7ae01.png)

**Comment by kerschfilip** [comment]
ještě jsem narazil [na jednu přílohu](https://k7journals.inovatika.dev/testovacinaserec/archiv;pid=uuid:ed5bac1e-a2ca-45f8-8c11-8c420a95869f), u které se název nezobrazuje, i když u všech ostatních v tom samém časopisu ano: 
![image](https://user-images.githubusercontent.com/57805328/220199395-78ffca35-f9d2-4e88-a8c1-08e4935bc120.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
díky!

**Comment by kerschfilip** [comment]
Znovu otevírám, protože v Časopisu Česká literatura se nám špatně rovnají čísla v ročnících, ačkoliv to dřív už fungovalo správně
https://asjournals.lib.cas.cz/ceskaliteratura/archiv;pid=uuid:feeac918-8b0a-4cb8-9e69-66340dde52e5

**Comment by kerschfilip** [comment]
@albertoh v ročníku už jsou čísla seřazená správně, ale na úvodní stránce se nejnovější číslo ukazuje špatně. Testuju na `ceskaliteratura/archiv;pid=uuid:feeac918-8b0a-4cb8-9e69-66340dde52e5`

V archivu: 
![image](https://user-images.githubusercontent.com/57805328/226359059-1588c6dc-1ff0-4a43-b369-0d4abbbc119f.png)

Ale na úvodní stránce:
![image](https://user-images.githubusercontent.com/57805328/226359144-6b3bae60-82a1-4fef-afd1-cedf19181fd8.png)

zkusil jsem ročník smazat a indexovat znovu, ale nepomohlo to

**Comment by albertoh** [comment]
Opraveno.

**Comment by kerschfilip** [comment]
@albertoh děkuju za opravu! prosím o vydání buildu s opravami, abychom to mohli nasadit.
