### ISSUE TITLE
Vyhledávání podle autorů

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/K5Journals#13]
Bylo by možné schovat vyhledávací dotaz, když vyhledávám autora?

![dotazautor](https://user-images.githubusercontent.com/21309201/68106034-a112bd00-fee0-11e9-8a48-d726a68c11f3.jpg)

Aby v tom poli byl jen autor?

**Comment by krizovj** [comment]
OK, ale když se prokliknu do vyhledávání z Archivu přes autora, tak to vypadá, že ten dotaz je tam špatně nastavený. 

Příklad:
![image](https://user-images.githubusercontent.com/21309201/70120844-bc9eee00-166d-11ea-8894-1f8f447f5277.png)
Kliknu v archivu u jednoho článku na "Tvrzníková, Jana".

![image](https://user-images.githubusercontent.com/21309201/70120944-ed7f2300-166d-11ea-9484-d8cf6828bfb8.png)
A ve vyhledávacím formuláři je správný dotaz. Má se vyhledávat v autorech "Trvzníková, Jana". Jenže výsledky vypadají, jako kdyby ten dotaz vypadal takhle:
![image](https://user-images.githubusercontent.com/21309201/70121055-1d2e2b00-166e-11ea-82b5-b442acd056ac.png)

Zkoušela jsem to přímo přes vyhledávání, tentokrát s jiným autorem a vypadá to, že "autor" a "kdekoliv" jsou prohozené:
Vyhledávám "Šícha, Vojtěch" - kdekoliv. Výsledkem je 14 článků, u nichž je uvedený jako autor:
![image](https://user-images.githubusercontent.com/21309201/70121340-ae9d9d00-166e-11ea-8da6-d0bf3413b9f5.png)

A když vyhledávám "Šícha, Vojtěch" - v autorech, tak výsledkem je 25 článků, u který není všude jako autor:
![image](https://user-images.githubusercontent.com/21309201/70121421-d12fb600-166e-11ea-9826-9b4982c92b81.png)

Ale pokud se prokliknu z rejstříku, tak to funguje dobře, najde 14 výsledků, u nichž je autor = Šícha, Vojtěch a dotaz tomu taky odpovídá. Vyhledávám v autorech.

Pokud jsem to vysvětlila nesrozumitelně, dejte vědět.

**Comment by albertoh** [comment]
Opraveno
