### ISSUE TITLE
Klíčová slova

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/K5Journals#14]
U jednoho z článků se špatně zobrazují klíčová slova, když je tam uvedená nějaká osoba s daty...
Narazili na to při testování v redakci Knih a dějin. Zřejmě to bude u všeho, kde je v klíčových slovech nějaký autor...?
![datumklicslovo](https://user-images.githubusercontent.com/21309201/68106225-36ae4c80-fee1-11e9-8003-69a87e170af0.jpg)

**Comment by albertoh** [comment]
Opraveno. Vyzaduje reindexace clanku

**Comment by krizovj** [comment]
Takže vymazat index a znovu tam nahrát celý ročník?

**Comment by krizovj** [comment]
Znovu jsem nahrála celý ročník. 
Už to vypadá v pohodě:
![image](https://user-images.githubusercontent.com/21309201/69856064-0f9f2c80-128d-11ea-8639-96966f530e18.png)
