### ISSUE TITLE
Kopírování citace - pozadí

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/K5Journals#15]
Když se kopíruje citace z okna, kopíruje se s ní taky růžové pozadí. Šlo by ho dát pryč? Ale zároveň tam musí zůstat to, co je kurzívou, příp. tučně.

**Comment by albertoh** [comment]
Nejde to. Pozadi je soucast formatovani stejne jako kurziva a tucne.

**Comment by krizovj** [comment]
OK, vyřídím. Díky
