### ISSUE TITLE
Úvodní web - "vydavatelé"

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/K5Journals#2]
Testováno tady: http://147.231.63.181/k5journals/magazines/vydavatele

Teď je tam seznam různých vydavatelů, ale nejsou u nich žádné časopisy. Takže tam ti vydavatelé nemají být vůbec.

Má to fungovat tak, že až když vyrobím nový časopis, tak se na této stránce objeví info o tom konkrétním vydavateli. Tohle je zřejmě seznam různých vydavatelů, který byl asi uvedený v zadání jako příklad. Stejně tak tam nemá být ta kategorie "Vydavatelé mimo AV ČR". Opět se objeví, až když tam nějaký takový vydavatel bude.

Po rozkliknutí vydavatele se objeví údaje o něm a časopisy, které vydává, což funguje v pořádku, ale když není časopis, tak by neměl být vidět ani vydavatel.

Zkoušela jsem to u časopisu Nový Orient.
Časopis Nový Orient je už založený. Vyrobila jsem tedy záznam pro vydavatele: Orientální ústav AV ČR, v. v. i.
Stejný název jsem zkopírovala taky do záznamu časopisu Nový Orient.
Pak jsem se koukla na stránku Vydavatelé a u vydavatele Orientální ústav AV ČR, v. v. i. se měl objevit časopis Nový Orient, ale nic se tam neukázalo.

**Comment by tumovam** [comment]
Na ostrém "úvodním webu" (= https://asjournals.lib.cas.cz/magazines ) jsou k dnešnímu dni (25.6.2021) dva vydavatelé: Knihovna AV ČR, v. v. i. a Ústav pro českou literaturu AV ČR, v. v. i., ale ve vydavatelích (https://asjournals.lib.cas.cz/magazines/vydavatele ) stále pouze Knihovna AV ČR, v. v. i.

**Comment by tumovam** [comment]
A s tím souvisí ještě jedna věc. Když ve vydavatelích (https://asjournals.lib.cas.cz/magazines/vydavatele ) kliknu na Knihovna AV ČR, v. v. i. (https://asjournals.lib.cas.cz/magazines/vydavatel/KNAV ), tak se zobrazí:

![obrazek](https://user-images.githubusercontent.com/31240271/123411808-29137200-d5b1-11eb-9ca3-dc00763c0f24.png)

1) kde se tento údaj upravuje? v konfiguraci? 
2) proč se zde za textem "Vydávané časopisy:" nezobrazí časopis Knihy a dějiny?

**Comment by kerschfilip** [comment]
v aktuální verzi tohle funguje v pořádku. Údaje se upravují v administraci celé aplikace v záložce Editoři
