### ISSUE TITLE
Jiná licence v patičce a v info u článku

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#27]
Pokud se upraví licence v Patičce (např. z  CC BY-NC-SA na CC BY-NC-ND ![obrazek](https://user-images.githubusercontent.com/31240271/123084457-6cd77180-d421-11eb-8961-c209cc7b18f7.png) ), změna se neprojeví v Informacích o článku. 

V info o článku ![obrazek](https://user-images.githubusercontent.com/31240271/123084387-57fade00-d421-11eb-8b94-7fd4650d7391.png) stále zůstává text Licence: CC-BY-SA - ![obrazek](https://user-images.githubusercontent.com/31240271/123084554-90022100-d421-11eb-99ef-a2200d301eaa.png).

**Comment by zemanovav** [comment]
Licence by se měla zobrazovat jen u obsahu, který pod licencemi CC opravdu publikován byl, nyní se informace o licenci zobrazuje všem článků v info o článku  
![image](https://user-images.githubusercontent.com/86363238/123109690-bb920500-d43b-11eb-84c1-71e1624e075a.png), přičemž licence CC časopis přiděluje až od posledního čísla.

**Comment by zemanovav** [comment]
Jen doplním, že toto je hlavní problém, který neumožňuje používat web pro časopisy Česká literatura a Cornova v praxi. Proto velmi prosím začít řešit tento bod mezi prvními. Děkuji za pochopení. Zemanová

**Comment by albertoh** [comment]
@zemanovav  Rozumim tomu spravne, ze muzou byt rozdilne licence pro casopis jako celek (to je ten udaj ktery mame) a pro konkretni clanek?

Pokud clanek ma jinou licence nez cely casopis, kde tato informace je?

**Comment by zemanovav** [comment]
@albertoh   Licence je stejná napříč všemi články casopisu. Problém je, že se u všech článků zobrazuje špatná. Česká literatura i Cornova maji vsechny články licencovane CC BY-NC-ND, ale pouze v 
České literature od c. 1 rok 2021 a novější,
Cornove od c. 2 rok 2020 a dalsi, které budou vycházet. U starších čísel by neměla být licence v metadatech clanku vubec uvedena.

**Comment by albertoh** [comment]
Mame ten udaje v BIBLIO_MODS toho cisla? kde?
Pokud ne, rozumim tomu, ze musi existovat moznost nekde nastavit manualne licence pro kazde cislo zvlast?

**Comment by zemanovav** [comment]
@albertoh požádala jsem o odpověď KnAV, která metadata zpracovává. Co vím, tak ale údaj o licenci do nich bohužel nezanáší.

**Comment by kerschfilip** [comment]
@albertoh v MODSu bohužel tyto údaje nebývají, rozhodně se na to nedá spolehnout  
bylo by řešením třeba přidat možnost nastavit pro časopis defaultní licenci a umožnit její dávkové úpravy (pro více čísel/ročníků najednou)?

**Comment by albertoh** [comment]
V administraci casopisu lze nastavit licenci pro jednotlive rocniky nebo cisla (tlacitko "nastavit licenci").
Pri zobrazovani bude ma prednost nejsi urovne kam patri clanek: 
 1.  cislo (periodicalitem)
 2.  rocnik (periodicalvolume)
 3.  cely casopis, jak je nastaveno v konfiguraci

**Comment by kerschfilip** [comment]
Super! Licence jdou nastavit tak, že odpovídají požadavkům, které popsala @zemanovav. Je také možné licenci nevyplňovat, v takovém případě se u informací o článku zobrazuje jen toto: 
![image](https://user-images.githubusercontent.com/57805328/144833179-8d11271b-efd0-4306-97f6-a52c88fe36d0.png)

Podle mě je to dostatečné řešení, díky! Trošku problém vidím v tom, že nastavování licencí je v administraci pro celý web a ne jednotlivé časopisy - běžný uživatel, který spravuje jen stránku svého časopisu, tak licence nastavovat nemůže, to může jen hlavní admin --> bylo by náročné tuhle agendu přesunout do administrace jednotlivých časopisů? (tzn. třeba sem: `.../cornova/admin` místo `.../magazines/admin`) @albertoh

**Comment by albertoh** [comment]
Ok, pridam to tam

**Comment by pkudela** [comment]
Hotovo viz. screenshots, nasazeno na server, prosim o otestovani.

![image](https://user-images.githubusercontent.com/16591052/145185754-a6e880b5-0abc-4208-a7e6-fe1385b2c333.png)

![image](https://user-images.githubusercontent.com/16591052/145185835-a8d95d8d-f163-42c7-900f-84b6b6838273.png)

**Comment by kerschfilip** [comment]
na časopisech Cornova, ČL i Knihy a dějiny mi to funguje, ale na nově založeném testovacím časopisu Věda pro každého se mi v admin rozhraní neotevře okno s licencemi:
![image](https://user-images.githubusercontent.com/57805328/145192396-2210f748-dcc5-4d91-a234-0d2cbc16ef0b.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
funguje, děkuju!

**Comment by kerschfilip** [comment]
Znovu otevírám, protože jsem narazil na nějaký problém s ukládáním upravených licencí:

1. Pokud se přihlásím k časopisu
2. V administraci vyberu "Nastavit licenci" 
3. Nějakému ročníku upravím licenci a uložím
4. odhlásím se a aktualizuju web pomocí F5 (nebo se na web podívám z jiného počítače)
5. pak po přihlášení se do administrace časopisu a kliknutí na "Nastavit licenci" vidím neupravenou tabulku s licencemi tak, jak se mi původně zobrazila v kroku 2)

Tohle se samozřejmě propisuje i do informací, které se zobrazují u článků, takže nastavování různých licencí v podstatě nefunguje.

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Díky @albertoh, funguje to líp než předtím, ale stále ne úplně ideálně:

### Co funguje
_přidání jiné licence jednomu číslu, u zbytku chci, aby měl licenci defaultní_ 
1. V admin prostředí po kliknutí na „Nastavit licenci“ vidím toto okno
 
![image](https://user-images.githubusercontent.com/57805328/149317240-346f7287-b373-41bb-9d0b-d517eeedd702.png)

2. Změním licenci u čísla 1 takto a dám uložit:
 
![image](https://user-images.githubusercontent.com/57805328/149317252-b253bf31-7bb1-4325-a0bd-b7d9cb2002ce.png)

3. U článků daného čísla se mi správně zobrazuje nastavená licence:
![image](https://user-images.githubusercontent.com/57805328/149317268-4189f827-c7fc-4363-9d1a-3104e98e40c4.png)

4. Stejně tak se správně zobrazuje v admin prostředí i po aktualizaci stránky, odhlášení a novém přihlášení atd.

### Co nefunguje
_Chci jinou licenci změnit zpět na defaultní, platnou pro celý časopis:_

5. Přihlásím se do admin prostředí časopisu a po kliknutí na „Nastavit licenci“ vidím tohle okno:
 
![image](https://user-images.githubusercontent.com/57805328/149317330-08750e46-a02b-4437-8c53-36b326676af5.png)

6. Odmažu text „jiná licence“ a vidím tak tohle. Uložím to:
 
![image](https://user-images.githubusercontent.com/57805328/149317340-4dad2a4f-86eb-46ec-bf29-cd3806d99ef0.png)

7. Odhlásím se a znovu se přihlásím do administrace časopisu
8. Po kliknutí na „nastavit licenci“ ale vidím okno licencí v původním stavu, jako by se moje akce neuložila:
 
![image](https://user-images.githubusercontent.com/57805328/149317353-b50abec4-e6df-4334-b760-b0baaba5fca0.png)

**Comment by albertoh** [comment]
Mate pravdu. Opraveno

**Comment by kerschfilip** [comment]
Bezva, teď už to funguje skvěle, díky!

Můžu poprosit o nějakou formu vydání těch oprav, abychom to mohli nasadit u nás? Děkuju!

**Comment by albertoh** [comment]
Je to tam

**Comment by mduda100871** [comment]
Ahoj,

tak to vypadá, že se mi to konečně podařilo zlomit a branche přeložit:

https://github.com/ceskaexpedice/K5Journals/tree/upgrade_2021

Rád bych upozornil na jednu věc - já nejsem js/angular vývojář a tudíž příprava vývojového prostředí, základní zorientování se v té neskutečné spleti závislostí a modulů mi dalo celkem zabrat.

Příště bych poprosil o již hotový testovací build, který nemusí být vydán oficiálně, ale abych nemusel trávit svůj čas výše uvedeným.

Zjistil jsem, že nejprve musím přeložit část aplikace `client/` aby se tam natáhly všechny node moduly a pak teprve jsem byl schopen přeložit celou aplikaci globálně pomocí `mvn clean package -DskipTests`.

Nicméně i tak překlad klienta vyhodil následující chybu/varování:

![asjournals-client-00](https://user-images.githubusercontent.com/8750622/149732519-891962d3-453f-4dca-9009-13e509944604.png)

Nevím tedy, zda-li to bude mít nějaký vliv na funkčnost aplikace.

Díky, MD

**Comment by albertoh** [comment]
Ahoj. Nevim proc bylo nutne jeste jednou buildovat. Dal jsem hotovy build do releases.
Ale ano, zapomnel jsem mergovat branch.
Jinak, to upozorneni nevadi

**Comment by mduda100871** [comment]
No právě, oficiální release byl bez opravy/starší, tak proto jsem překládal ten branch.

MD
