### ISSUE TITLE
Datum zveřejnění článku

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#28]
Z redakce přišel požadavek, aby se v Informacích o článku (vpravo dole) zobrazilo i datum. "DateIssued" v metadatech článku není, ale je na úrovni čísla. Nešlo by tento údaj z čísla převzít a přidat k článku?

Zdůvodnění: jde o časopisy, které mají přidělené eISSN. V podmínkách se uvádí, že články by měly mít datum zveřejněné.

**Comment by kerschfilip** [comment]
já se omlouvám, ale nikde to nevidím - kde se to, prosím, ukazuje?

**Comment by albertoh** [comment]
Omlouvam se, reindexace neprobehla

**Comment by albertoh** [comment]
Opraveno. Lze testovat na casopisu "Česká literatura"

**Comment by kerschfilip** [comment]
Bezva, funguje, díky!
![image](https://user-images.githubusercontent.com/57805328/145185971-11279d33-65c8-4416-8e51-23ae1107e3e4.png)
