### ISSUE TITLE
Zalamování textu v patičce webu

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#29]
Pokud je v patičce delší text (např. si redakce přidá ISSN i e-ISSN), tak se patička nepěkně zalamuje.

Toto vypadá dobře: 
![obrazek](https://user-images.githubusercontent.com/31240271/123417913-b3130900-d5b8-11eb-8a9d-423c7f5bd2e8.png)

Toto už moc ne: 
![obrazek](https://user-images.githubusercontent.com/31240271/123417962-c02ff800-d5b8-11eb-8a8e-d403929ec341.png)

Domnívám se, že to nesouvisí s velikostí monitoru, screeny jsou z dost velké obrazovky.

**Comment by kerschfilip** [comment]
OK, díky

**Comment by pkudela** [comment]
@kerschfilip prosim, pokud je issue z vasi strany v poradku, tak ho zavrete, at se nam neplete mezi otevrene issue, dekuji.

**Comment by kerschfilip** [comment]
@pkudela nemám bohužel dostatečná práva na to zavírat issues, která jsem nezaložil -> pokud mi je přidělíte, tak pozavírám vše, co považuji za vyřešené, díky

**Comment by pkudela** [comment]
aha, to jsem nevedel, taky nevim, jestli mam prava udelit Vam prava :) podivam se na to

**Comment by pkudela** [comment]
@kerschfilip prosim zkuste to ted, dal jsem vam jinou roli, pokud nezafunguje, dejte vedet, asi by Vam melo prijit neco do mailu

**Comment by kerschfilip** [comment]
super díky, issue zavírám
