### ISSUE TITLE
Editování rubrik

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#32]
V ČJ i AJ verzi je na výběr pouze několik nadefinovaných rubrik. Bylo by možné tyto rubriky editovat? Např. místo Redakce -> Redakční rada, namísto Open Access -> Licence ... atd.?

**Comment by kerschfilip** [comment]
Je potřeba vyřešit možnost přejmenování rubrik, pro některé časopisy totiž neodpovídají popisky skutečnosti (například Česká literatura nemá “recenzní řízení” ale “lektorské řízení”). Možnost změnit pojmenování by měl mít administrátor konkrétního časopisu. Menu se tedy bude muset generovat dynamicky. Současně s přejmenováním se bude řešit i podoba URL jednotlivých rubrik

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/203504456-df1a197f-9c93-4d79-a68f-7021f4206ada.png)

**Comment by albertoh** [comment]
@pkudela  koukni na sipky a inputy v admin casopisu

**Comment by pkudela** [comment]
hotovo, nasazeno na serveru -> https://k7journals.inovatika.dev/knihyadejiny/admin

**Comment by kerschfilip** [comment]
Editování rubrik a jejich přidávání otestováno, funguje, moc díky!

Bylo by možné také rubriky mazat - pokud teď třeba nějakou přidám omylem, tak ji můžu jen zneviditelnit, ale už se ji nezbavím. 

A ještě jaký je rozdíl mezi k5journals.inovatika a k7journals? Protože na k5 mi jde editovat texty jednotlivých rubrik, ale na k7 to vypadá, že se texty neukládají.

**Comment by albertoh** [comment]
Pridal jsem tlacitko pro odstraneni.
Opravil jsem ukladani textu v k7journals

Oba by se mely chovat stejne. Rozdil je pri ziskani stranky: v k7 html je cely

**Comment by albertoh** [comment]
> ukládání textu v K7 OK, kromě nově přidané rubriky na nejvyšší úrovni, tam se mi text na stránce nezobrazuje, i když v admin rozhraní je uložený.

 Nebude to tim, ze mate stejny nazev? Ja jsem ted pridal, a vidim
![image](https://user-images.githubusercontent.com/5946836/208044644-6aa9879a-854a-458c-b387-3717bfdfd680.png)

![image](https://user-images.githubusercontent.com/5946836/208044562-81f5db8b-6965-4d66-aef2-81f68de051bc.png)

![image](https://user-images.githubusercontent.com/5946836/208044486-e0325d1d-4ea3-4dea-b76a-4fa80a42fb18.png)


> A s tím souvisí - mohly by, prosím, ty nově přidané rubriky na úrovni hlavního menu být dvě místo jedné?

 Nerozumim, ted muzete pridat podrubriku, ale ne rubriku.  A muzete je pridat kolik chcete

**Comment by kerschfilip** [comment]
Aha, tak tohle možná vzniklo jako chyba při vývoji/testu? Ale u některých časopisů se ukázala nová rubrika, kterou je možné libovolně pojmenovat. třeba tady: https://k7journals.inovatika.dev/korpus:
![image](https://user-images.githubusercontent.com/57805328/208620676-2a30fe5a-6d63-450f-97db-bd956d2121c8.png)

Ačkoliv to nebylo v původním zadání, ukázalo se to jako užitečné, protože shodou okolností zrovna teď dva časopisy běžící na as-journals řeší zapojení do databáze SCOPUS a vyžadují po nich, aby v hlavním menu měli záložku, kterou tam teď nemají...
Můžete tam teda tuhle jednu, nebo ideálně dvě volitelné položky na úrovni hlavních rubrik nechat?

**Comment by albertoh** [comment]
Je to tak, vzniklo pri vyvoj...
Ale ted uz je tam pravem pridano.

**Comment by kerschfilip** [comment]
bezva, moc děkuju! pořád se mi ale nedaří v téhle nové rubrice uložit text tak, aby se na stránce potom zobrazoval. Popíšu postup a případně napište, co dělám špatně:

- na webu časopisu cornova v na k7journals.inovatika vstoupím do administrace
- přepnu na rozhraní
- kliknu na "novou rubriku" `menu_4_new`
- do textového pole vložím nějaký text a kliknu na uložení  ![image](https://user-images.githubusercontent.com/57805328/212933974-45aa8f1e-c3e3-42fb-a0fe-bbcc966bd1ef.png)
- objeví se zelený pruh, že uložení proběhlo úspěšně
- nyní kliknu v horním menu na novou rubriku nazvanou "Název CS"
- místo textu, který se ale právě uložil se pořád ukazuje _Text not found in..._
- pokud se vrátím do administrace text ale je v tom textovém poli uložený 🤯

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Díky!

**Comment by kerschfilip** [comment]
pardon, ještě zpět otevírám, všiml jsem si totiž následujícího problému:

U nově založeného časopisu (třeba jsem založil veda_vyzkum_test), se mi nedaří kliknout v admin rozhraní na editaci položek "Aktuálně" a "Zařazení v databázích". Ani ukládání textu při editaci ostatních rubrik nefunguje spolehlivě - ne vždy se text uloží, ne vždy se ukáže zelený pruh s potvrzením uložení. U podrubrik to ale funguje vždy. Stejně tak to funguje u dříve založených časopisů (např. cornova)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
- už jde kliknout v admin rozhraní na editaci položek "Aktuálně" a "Zařazení v databázích"
- nově přidanou rubriku je možné smazat

Díky!

Ještě ale stále platí, že ukládání textu při editaci ostatních rubrik nefunguje spolehlivě, přidávám příklad:
- v administraci časopisu veda_vyzkum_test kliknu na editaci rubriky "pro-autory"
- vyplním tam nějaký text a kliknu na uložit
- neukáže se zelený pruh o úspěšném uložení a nově vyplněný text se na stránce neukáže

**Comment by albertoh** [comment]
Opraveno. Zustala tam spatny konfiguracni soubor

**Comment by kerschfilip** [comment]
Funguje, díky!
