### ISSUE TITLE
Přidání rubrik

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#33]
Aby byl zachovaný jednotný design všech webů, asi by nebylo dobré přidávat rubriky, ale nebylo by možné přidávat PODrubriky?
Např.: 
![obrazek](https://user-images.githubusercontent.com/31240271/123424573-4fd9a480-d5c1-11eb-9d49-8f7329483427.png)

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/203504318-47c9cedc-cd5b-48cd-a50e-ba57fcc90b95.png)

**Comment by albertoh** [comment]
Opraveno v #32
