### ISSUE TITLE
Předchozí a následující číslo v Archivu

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#34]
Když si prohlížím např. 6. číslo, chtěla bych vidět jeho označení. 

Ideální stav, který chceme: 
![obrazek](https://user-images.githubusercontent.com/31240271/123425559-8fed5700-d5c2-11eb-869f-07433052b2af.png)

Současný stav, který je, dle mého názoru, nešťasný, protože nevím, jaké číslo si prohlížím: 
![obrazek](https://user-images.githubusercontent.com/31240271/123425821-e3f83b80-d5c2-11eb-85f8-0e86b157bef8.png)

**Comment by kerschfilip** [comment]
![image](https://user-images.githubusercontent.com/57805328/144860603-0ce2c748-0335-46fe-b2d1-ba279e23097d.png)
Vyřešeno, díky!
