### ISSUE TITLE
Výsledky řazení od nejstaršího/od nejnovějšího v Archivu

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#35]
Na první pohled se zdá, že Výsledky řazení od nejstaršího/od nejnovějšího nefungují, ale není to pravda. Je nutné mít správně seřazené ročníky v jádře Krameria! Tzn. ročníky je potřeba seřadit v Editoru částí a titul zreindexovat. 

Issue se může zavřít, ale chtěla jsem to sem napsat, kdyby se někdo setkal s podobným problémem.

**Comment by albertoh** [comment]
Muzete mi napsat priklad, kde nei spravne razeni?

**Comment by kerschfilip** [comment]
@albertoh na testovacím serveru Inovatiky žádný příklad nemáme, ale u nás na interním testovacím ano - například časopis Korpus - gramatika - axiologie [se v klientovi](https://kramerius.lib.cas.cz/uuid/uuid:1235aa69-d231-4003-b5d0-aa5ec983beb9) řadí hezky, ale [v jádře](https://kramerius.lib.cas.cz/search/i.jsp?pid=uuid:1235aa69-d231-4003-b5d0-aa5ec983beb9&q=Korpus%20-%20gramatika%20-%20axiologie) ho máme rozházený. K5Journals potom převezme to pořadí z jádra, viz screenshot: 
![screencapture-asjournals-test-lib-cas-cz-Korpus-gramatika-axiologie-archiv-2022-11-22-08_50_06](https://user-images.githubusercontent.com/57805328/203256132-5ac9cdfa-5bbb-47c9-ae3f-6620694b7265.png)

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/203505352-45e82126-2c08-4a01-8a59-2491153a8abb.png)

**Comment by kerschfilip** [comment]
OK, díky!
