### ISSUE TITLE
Dlouhý název a podnázev časopisu

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#36]
Když má časopis delší název (spíše to bude podnázev), špatně se zobrazuje v horní části webu.

Např. toto je OK 👍  : 

![obrazek](https://user-images.githubusercontent.com/31240271/123426968-53225f80-d5c4-11eb-97f0-ee84748c2fc4.png)

Toto je špatně 👎 : 

![obrazek](https://user-images.githubusercontent.com/31240271/123427018-633a3f00-d5c4-11eb-9847-6f973f298369.png)

(Ano, vím, že ve 2. případě je v před názvem časopisu zobrazeno slovo "časopis", ale může se stát, že budeme mít časopis s delším (pod)názvem a asi bychom na to měli být připraveni). 

Nebylo by řešením dát název na 1 řádek a podnázev pod něj = na 2. řádek?

**Comment by pkudela** [comment]
Dobry den @tumovam , rozhodne bych nedoporucoval davat podtitulek pod nazev casopisu. Upravil jsem header s logem tak, aby se zobrazoval cely a zalamoval se na 2 radky vcetne chovani pro mobilni zarizeni viz. screenshots:

![image](https://user-images.githubusercontent.com/16591052/144284384-7b79f491-3a70-4e9d-9707-ef52e6bbc07d.png)
![image](https://user-images.githubusercontent.com/16591052/144284473-1a4664b9-d520-49f5-b6b4-02e28fd2e7a9.png)

Nicmene byl bycho pro, subtitle neoodelovat dvojteckou, ale spise ho udelat mensim pismem tak aby bylo uzivateli na prvni pohled jasne, ze se jedna o podtitulek. NIze posilam screenshot, jak by to bez dvojtecky a se zmensenym pismenem podtitulku vypadalo, muze byt oddelene i pomoci pipe.

![image](https://user-images.githubusercontent.com/16591052/144286136-21f27706-b726-438d-b35b-ec2ba5451daf.png)

**Comment by pkudela** [comment]
@tumovam je to hotove, priklad podtitulku muzete videt zde -> https://k5journals.inovatika.dev/knihyadejiny/home 
V administraci -> https://k5journals.inovatika.dev/magazines/prihlaseni po prihlaseni si u kazdeho casopisu muzete podtitulek zmenit viz. screenshot. Prosim o otestovani a pokud vse ok, tak o zavreni tohoto issue.

![image](https://user-images.githubusercontent.com/16591052/144455676-e4dd2619-1dc8-4477-9b27-564b16ab618b.png)

**Comment by tumovam** [comment]
@pkudela děkuji, možnost upravovat podnázev mi přijde jako dobré řešení. Otestujeme a dáme vědět. Děkuji, MH

**Comment by kerschfilip** [comment]
Možnosti upravovat podnázev funguje a je to super řešení, díky!

Jen na mobilu se to nezobrazuje úplně ideálně - nakonec je podnázev větší než samotný název:
![image](https://user-images.githubusercontent.com/57805328/144860019-b1811fc3-b55a-4606-8a08-7465059fbef0.png)

**Comment by kerschfilip** [comment]
ještě doplním, že to vypadá, že obecně je tam nějaký problém s interpretací velikosti nadpisů a textu na mobilu:
takhle připravená stránka
![image](https://user-images.githubusercontent.com/57805328/145000062-f71f0cea-2daa-4d5e-81de-f502ea498df2.png)
vypadá na mobilu takhle: 
![image](https://user-images.githubusercontent.com/57805328/145000271-34d95e12-295f-439a-9a3c-de91b2336f96.png)

**Comment by pkudela** [comment]
Dobry den, toto je zpusobeno responsivnim chovanim puvodni casti titulku, jak se pridal podtitulek, tak se to chova nekorektne, podivam se na to.

**Comment by pkudela** [comment]
Dobry den, nasadil jsem novou verzi. Musel jsem prizpusobit chovani novemu subtitulku, nyni by se to melo chovat korektne, nicmene pokud bude podtitulek tak dlouhy jak je v prikladu, musi se pocitat se zalamovanim textu.

![image](https://user-images.githubusercontent.com/16591052/145044258-df3dabf7-6042-4b89-b8db-1be59a46c908.png)

![image](https://user-images.githubusercontent.com/16591052/145044315-a9ee06ea-a0bb-4a57-9e5c-548e9f5cd455.png)

![image](https://user-images.githubusercontent.com/16591052/145044390-a954d94c-779e-4e76-9185-d2e027acfd86.png)

**Comment by pkudela** [comment]
Prosim otestujte a pokud je to ok, zavrete toto issue, dekuji.

**Comment by kerschfilip** [comment]
Mockrát děkuji, vypadá to dobře. Issue zavírám.

ještě jsem si všiml toho problémů [s velikostí nadpisů v textu](https://github.com/ceskaexpedice/K5Journals/issues/36#issuecomment-987718989) u mobilního zobrazení - založím nové issue, aby se to nemotalo dohromady
