### ISSUE TITLE
Aktuální číslo a Archiv - zobrazení na mobilu

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#38]
Na mobilu nefunguje "Prohlížet" v rubrice Aktuální číslo a Archiv. Na mobilu jsou vidět články, ale už ne jejich plné texty.

**Comment by pkudela** [comment]
Dobry den @tumovam, muzete mi prosim upresnit co Vam presne nefunguje? Testoval jsem to a vse funguje zda se jak ma viz. screenshot nize. Na malych zarizenich se clanky zobrazi jako prvni a pod tim se zobrazi ctecka.

![image](https://user-images.githubusercontent.com/16591052/144018158-2f035f7d-172b-44d0-ba67-37cfeb8586c4.png)

![image](https://user-images.githubusercontent.com/16591052/144018268-3bbe3e8e-665a-4f02-8e47-675fa90cc11d.png)

**Comment by kerschfilip** [comment]
Dobrý den, @pkudela, odpovídám za @tumovam. Nevím už, v čem nahlášený problém spočíval, ale souhlasím, že všechno funguje tak, jak popisujete. 

Je otázka jak moc je to vhodné - třeba po kliknutí na článek by mohlo prostředí přeskočit na text článku, teď si tam musí uživatel scrollovat docela dlouho sám. Navíc třeba při přiblížení textu se prostředí trošku rozhodí, viz screenshot: 
![image](https://user-images.githubusercontent.com/57805328/144051931-4a91ca9c-c835-4da4-9431-2cdccc3c94be.png)

Nicméně to je spíš na nějakou optimalizaci UI a v tuhle chvíli to není to nejnutnější, co potřebujeme řešit.

Díky!,
FK, KNAV

**Comment by pkudela** [comment]
Dobry den, me napadlo jine reseni, udelal jsem pevnou vysku jak pro clanky, tak pro prohlizecku, takze nyni scrollujete v ramci dane oblasti stejne, jako v desktop zobrazeni, takze obe oblasti jsou pro uzivatele vcelku dobre dostupne a ovladaci prvky pro ctecku zustavaji na miste i pri scrollovani. Az to bude na testovacim serveru, tak to sem napisi, abyste mohl starou a novou verzi porovnat. 

![image](https://user-images.githubusercontent.com/16591052/144056619-709bbe40-6cac-458a-b368-c8cc6fbfbcbb.png)
![image](https://user-images.githubusercontent.com/16591052/144056807-e90fa369-8687-47eb-bec5-5546209cc59d.png)

**Comment by pkudela** [comment]
Nakonec jsme chovani pro mobilni zarizeni jeste trochu upravili. Nyni je mozne prepinat mezi seznamem clanku a cteckou viz. screenshots. Testoval jsem to na mobilu i na iPodu, otestujte to take, jestli Vam to takto vyhovuje.

![image](https://user-images.githubusercontent.com/16591052/144458766-4e95800b-b10c-4b04-9fde-b12a742244a1.png)

![image](https://user-images.githubusercontent.com/16591052/144458860-bc8f8994-2c43-43ea-8207-368cdd2f9600.png)

**Comment by kerschfilip** [comment]
je to mnohem lepší, díky. Ale stále mi ta postranní lišta překrývá kus textu a nevypadá to podle mě úplně dobře. 
![image](https://user-images.githubusercontent.com/57805328/144876674-66a5b6cd-3646-4e87-9cfa-ced26eede35e.png)

**Comment by pkudela** [comment]
Dobry den, na cem prosim aplikaci zkousite a pripadne v jakem browseru? Ja to ted zkousim na stejnem casopise, jak v prohlizeci chrome na mem notebooku, tak na mobilu s velmi malym rozlisenim a vse se mi zobrazuje spravne, sirka clanku se prizpusobuje velikosti okna prohlizece viz. screenshoty nize.

![image](https://user-images.githubusercontent.com/16591052/145072484-f04bffdf-0370-4bd2-8195-2439375a9c9a.png)

![image](https://user-images.githubusercontent.com/16591052/145072597-727ae2d3-55b2-4651-a0cd-5efe672977d1.png)

![image](https://user-images.githubusercontent.com/16591052/145073403-afdab223-6c2b-4edb-871d-749f7f70ad19.png)

**Comment by pkudela** [comment]
Pokud mate na mysli zoomovani, tak tam se clanek opravdu nezobrazoval cely v pripade, ze jste bud mysi, nebo prstem na mobilu zkusil posunout clanek do leva, tak prava strana clanku byla skryta za cerveny sidebar s ovladacimi prvky viz. screenshot nize:

![image](https://user-images.githubusercontent.com/16591052/145076261-c1543c04-3d51-40ea-ba91-bff89435f8c4.png)


Toto jsem jiz opravil viz. screenshot nize:

![image](https://user-images.githubusercontent.com/16591052/145076458-661bd61d-8c27-4b10-8841-31509990a130.png)

**Comment by pkudela** [comment]
Nasazeno na server, prosim otestovat a pokud bude v poradku, tak zavrit toto issue.

**Comment by kerschfilip** [comment]
testoval jsem v chromu a na iphonu 7, měl jsem na mysli přesně to zoomování, pardon za nepřesný popis. Je to vyřešené, díky!
