### ISSUE TITLE
Aktuální číslo na Hlavní stránce

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#39]
Nyní: 

![obrazek](https://user-images.githubusercontent.com/31240271/123770130-4bb3cc80-d8ca-11eb-8407-5e5596237824.png)

Nešlo by: 

AKTUÁLNÍ ČÍSLO **1-2/2020**  , příp. AKTUÁLNÍ ČÍSLO **1-2, 2020** 

???

**Comment by zemanovav** [comment]
![image](https://user-images.githubusercontent.com/86363238/138312056-f41443c4-303f-489c-b70f-c27f61de6b8a.png)
Tak, jak se popisek (aktuální číslo 08.2021 3) propisuje z Krameria, je sice správně, ale nevypadá to na webu dobře (https://asjournals.lib.cas.cz/ceskaliteratura/home). 
Šlo by to, prosím, upravit, aby bylo uvedeno jen číslo a ročník? Ideálně např.
AKTUÁLNÍ ČÍSLO 3, 2021 nebo
AKTUÁLNÍ ČÍSLO 3/2021 a podobně k tomu případná dvojčísla
př.: AKTUÁLNÍ ČÍSLO 3-4, 2021 nebo 3-4/2021

**Comment by kerschfilip** [comment]
V současné verzi takto: 
![image](https://user-images.githubusercontent.com/57805328/144856597-2c3c6b5e-4b2b-4fc6-91eb-bd4a064a7230.png)
Podle mě OK, díky
