### ISSUE TITLE
Odstranění UUID

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/K5Journals#40]
Stejně jako je v admin rozhraní webu časopisu možnost Přidání uuid (obr.: ![obrazek](https://user-images.githubusercontent.com/31240271/123958335-395e8f00-d9ad-11eb-84d6-4bd2233952a6.png) ).

Měla by zde být funkce "Odstranit uuid".

**Comment by albertoh** [comment]
Pridana moznost odstraneni uuid. Zaroven odstrani vsechny podrazene zaznamy.

![image](https://user-images.githubusercontent.com/5946836/144561088-5d28f8c5-f43e-4cd4-861c-94102f3d1ec4.png)

**Comment by kerschfilip** [comment]
Funguje, díky!
