### ISSUE TITLE
čas. Česká literatura a archiv - nefunkční Prohlížení

### ISSUE THREAD

**Issue by zemanovav** [ceskaexpedice/K5Journals#41]
Čas. Česká literatura neobsahuje v archivu kompletní čísla za rok 2015 (chybí číslo 6), dále nefunguje režim prohlížení - konkrétně to nezobrazuje články (jen obsah, případně reklamu).
![image](https://user-images.githubusercontent.com/86363238/127610481-6888de47-851d-4c8d-8525-aa5fa2463c49.png)

**Comment by albertoh** [comment]
To je zpusobeno tim, ze dane clanky nemaji definovan 'genre'.

V aplikace to je nutne, jinak neni mozne seradit clanky podle genre.
Muzu automaticky, pri absenci "mods:genre", nastavit pro clanek genre jako "main article".

Nevim ale, jestli v jinech casopisech je naschval vynechan tag genre v mods, aby se nezobrazovalo

**Comment by kerschfilip** [comment]
Kde prosím chybí ten `mods:genre`? Například v článcích z toho ročníku 2015, čísla 5 je u článků tohle:  
![image](https://user-images.githubusercontent.com/57805328/144050195-d9a1f1ed-0081-44ab-8027-e14c15cac142.png)

zatímco hodnota `main article` být podle platných standardů přítomna nemusí, samotný tag `<genre>` by měl být v metadatech vždy - takže varianta že by se vynechával schválně, by nastávat neměla...

**Comment by albertoh** [comment]
Uz vidim problem.
Davno, pri vyvoj aplikace bylo receno, ze podminka pro zobrazeni na seznamu pri prohlizeni je pritomnost tagu genre, ale s attribute "type". A to, z toho duvodu, aby se nezobrazovali elementy typu "Přední klopa". Napriklad:

https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:9bbf3351-32ef-40c9-a317-5abd8b4a231f/streams/BIBLIO_MODS

Tim padem, i zaznam:
https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:55f23274-de9c-454f-badf-a7441bd24777/streams/BIBLIO_MODS

je vyfiltrovan jako bez genre (nema "type")

Dale  mame v aplikaci definavano nekolik neviditelnych rubrik na tom seznamu: 

"hiddenGenres": ["cover", "advertisement", "colophon"]

Muzu menit indexer tak, aby pridal zpet genre bez "type". Ale tim se budou zobrazovat i clanku typu "Přední klopa".

Udelam to na nasim testovacim, a reknete

**Comment by kerschfilip** [comment]
za mě je to takhle OK, články se zobrazují, díky!
