### ISSUE TITLE
Modul správy uživatelů

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#43]
V současné verzi je správa uživatelů řešena konfiguračním souborem [`users.json`](https://github.com/ceskaexpedice/K5Journals/wiki/K5Journals#konfigurace), rádi bychom, aby bylo možné uživatele spravovat skrze UI aplikace, a ne pouze v konfiguraci.

**nový modul by měl umožňovat**
- uživateli s nejvyšším oprávněním (superadmin) 
  - zakládat nové uživatele
  - přidělovat jednotlivým uživatelům role (= časopisy, které mohou spravovat)
  - mazat uživatele
  - resetovat uživateli heslo
- běžnému uživateli změnit si heslo

**Comment by albertoh** [comment]
Chybi moznost zmeny hesla pro bezny uzivatel. Ted je to v rezii administratora

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/144561963-92835f62-bb52-4308-bb49-ca91c0a20284.png)

**Comment by kerschfilip** [comment]
Možná je to moje chyba, ale daří se mi jen uživatele vytvořit - přihlásit se nově vytvořeným uživatelem nejde :/

**Comment by albertoh** [comment]
Omlouvam se, bylyu prehozene stitky pro jmeno a uzivatelske jmeno (login). Opravim

**Comment by kerschfilip** [comment]
funguje, díky  

Ještě chybí možnost změnit si heslo u běžného uživatele -> to teď ale možná není nejnutnější řešit.

**Comment by albertoh** [comment]
Hotovo.

**Comment by kerschfilip** [comment]
Přijde mi, že to nefunguje spolehlivě, někdy se heslo změní a někdy ne. Například jsem to zkoušel na nově založeném uživateli UzivatelMeniciHeslo. Poprvé se mi heslo změnit povedlo, ale znovu mi to nejde - ani z administrace časopisu, ani z hlavní administrace. 

Taky se mi nedaří smazat uživatele

**Comment by albertoh** [comment]
Nemuzu reprodukovat... Mne se to podarilo, treba pro daneho uzivateli, uzivatelMeniciHeslo. Nastavil jsem heslo test, a muzu tam se prihlasit.
 Je mozne, ze chcete se prihlasit na administraci vsech casopisu? Ten uzivatel ma pravo jen se prihlasit na casopis pro ktery ma prava, tj, ceskaliteratura ?

**Comment by kerschfilip** [comment]
Ne, nejde o administraci všech časopisů.Vyzkoušel jsem to teď ještě jednou a přidávám svůj postup:
1) založený nový uživatel "testHesla" - práva jen k časopisu "cornova"
2) Tlačítko "resetovat heslo" -> heslo nastaveno na "heslo"
3) V časopise Cornova --> Přihlásit --> Přihlášení funguje pomocí nastaveného hesla
4) Admin --> Resetovat heslo --> nastaveno nové heslo "reset"
5) Odhlášení
6) Znovu přihlášení do časopisu Cornova pomocí změněných údajů --> nové heslo "reset" nefunguje, ale je možné se přihlásit původním heslem "heslo"

**Comment by albertoh** [comment]
Podarilo se mi taky to :)
Problem byl v tom, ze pri odhlaseni vyprsela session i pro administratora (asi jste to delal v tom samem browseru), a pri pokusu o zmene hesla nic se nestalo.
Ted jsem to zmenil tak, ze pri pokusu o zmene hesla kdyz session je pryc, oznami to odhlaseni, a presmeruje na home.
To asi je akorat problem testovani, kdyz mame otevrene dva zalozky v jednom prohlizece.
Opravil jsem zaroven mazani uzivatelu

**Comment by kerschfilip** [comment]
Mazání uživatelů je opravené, ale s těmi změnami hesel mi přijde, že to furt blbne. Nejdřív se mi to povedlo, ale není to spolehlivé:

Třeba když jsem
1) založil nového uživatele "test2020" s přístupem k časopisu Česká literatura
2) resetoval mu heslo na "test"
3) tak mi nejde se na stránce časopisu přihlásit

**Comment by albertoh** [comment]
Testujete to ve dve zalozkach jednoho prohlizece?

**Comment by kerschfilip** [comment]
vám to nějak funguje? když tak napište postup :-) Mně to nejde ve dvou záložkách stejného prohlížeče, ve dvou různých prohlížečích ani dvou různých počítačích...

**Comment by kerschfilip** [comment]
@albertoh bylo by možné tohle nějak dokončit a uzavřít? Nevím, jestli dělám něco špatně já, nebo je v tom ještě někde nějaká chyba... Přidávám postup, který jsem teď vyzkoušel a o kterém si myslím, že by měl fungovat:

testování v anonymním okně Microsoft Edge (ten jsem ještě nepoužil, tak pro jistotu)
přihlášení na hlavní stránce pomocí uživatele "test"
vytvoření nového uživatele "leden", přiřazený časopis "vedaprokazdeho" --> uložit uživatele
resetovat heslo --> nové heslo nastaveno na "leden"
odhlášení

V jiném anonymním okně otevření časopisu Věda pro každého 
Přihlásit --> uživatel "leden", heslo "leden" --> Funguje
Admin --> Resetovat heslo --> nové heslo nastaveno na "unor" --> "Heslo bylo změněno"
odhlášení

V dalším anonymním okně otevření časopisu Věda pro každého 
Přihlásit --> uživatel "leden", heslo "unor" --> "Špatné přihlašovací údaje."
Přihlásit --> uživatel "leden", heslo "leden" --> Funguje (ale nemělo by)

**Comment by albertoh** [comment]
Dobry den. Prave to testuju a funguje mi to. Muzeme si dat kratky call? skype? meet?

**Comment by albertoh** [comment]
Ale problem zrejme je v tom, ze anonymni rezim sdili session na serveru mezi zalozky.

**Comment by kerschfilip** [comment]
tak já nevím, mně to prostě nějak nefunguje - zavolat si můžeme, posílal jsem mail na alberto.hernandez@inovatika.cz

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
funguje, díky moc!
