### ISSUE TITLE
smazat "Starší ročníky najdete v Digitální knihovně AV ČR" na stránkách čas. Cornova

### ISSUE THREAD

**Issue by zemanovav** [ceskaexpedice/K5Journals#46]
V archivu časopisu Cornova (https://asjournals.lib.cas.cz/cornova/archiv) je na konci stránky informace "Starší ročníky najdete v Digitální knihovně AV ČR", která je irelevantní (zavádějící), neboť v archivu jsou všechny ročníky časopisu od začátku. Tedy věta "Starší ročníky najdete v Digitální knihovně AV ČR" by se v případě čas. Cornova mohla smazat.

**Comment by albertoh** [comment]
Pridana moznost nastaveni v administraci

![image](https://user-images.githubusercontent.com/5946836/144561651-9db3d00c-1764-4ee3-bd3a-293cf0e94553.png)

**Comment by kerschfilip** [comment]
Funguje, díky!

**Comment by kerschfilip** [comment]
Ještě jsem si všiml, že se text "Starší ročníky najdete v Digitální knihovně AV ČR" ukazuje i na stránkách, kde je zbytečný. Podle mě by úplně stačilo, aby byl (pokud je zapnutý) na stránce [archivu](https://k5journals.inovatika.dev/ceskaliteratura/archiv). Při procházení [konkrétního ročníku](https://k5journals.inovatika.dev/ceskaliteratura/archiv;pid=uuid:ac1b1d55-0e95-43cd-86e8-79e282052b01) nebo dokonce [článků v čísle](https://k5journals.inovatika.dev/ceskaliteratura/archiv;pid=uuid:eb736fb2-b050-4a51-a9e0-528beeb9ff20) je docela zbytečný, až matoucí...

**Comment by kerschfilip** [comment]
@albertoh je tohle možné nějak upravit, nebo by to bylo příliš složité? Je to asi poslední věc, kterou máme k tomu [současnému upgradu](/ceskaexpedice/K5Journals/tree/upgrade_2021)

**Comment by albertoh** [comment]
Hotovo

**Comment by kerschfilip** [comment]
super, díky!
