### ISSUE TITLE
Cornova - chybějící článek

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#47]
na webu Cornova jsme narazili na problém:
[v ročníku 8 (2018), čísle 1](https://asjournals.lib.cas.cz/cornova/archiv;pid=uuid:60b92dae-bc22-42f8-963e-dd34165ca17d) chybí dva články, které normálně v Krameriovi jsou (konkrétně [Von wem und warum wurde... ](https://kramerius.lib.cas.cz/view/uuid:60b92dae-bc22-42f8-963e-dd34165ca17d?article=uuid:9285147e-6cf2-454f-853a-a1b18207c71e)a [Vzpomínka, která nevyhasla](https://kramerius.lib.cas.cz/view/uuid:60b92dae-bc22-42f8-963e-dd34165ca17d?article=uuid:fb54252e-0248-4b17-8373-6df0b4a378a9)) 

Zkusil jsem dané číslo reindexovat v Krameriovi a znovu přidat ko K5Journals, ale nic se nezměnilo. Co s tím můžeme dělat, @albertoh?

Mockrát děkuji!

FK

**Comment by albertoh** [comment]
Problem je ve formatu MODS. Zrejme se zmenilo zpusob zapsani mods:subject/mods:name/mods:namePart
Bude opraveno pri aktualizaci.

**Comment by kerschfilip** [comment]
v testovací verzi se články ukazují, vypadá to OK
