### ISSUE TITLE
Mobilní zobrazení - špatné velikosti nadpisů

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#49]
Velikost nadpisů v textu běžné stránky se na mobilním zařízení změní tak, že nadpis je nakonec menší než samotný text 

Takto připravené stránka
![image](https://user-images.githubusercontent.com/57805328/145183444-72c0dad1-9be6-4447-ad5b-6362265159cd.png)

Se mi zobrazuje takto:
![image](https://user-images.githubusercontent.com/57805328/145183474-a2bcbe2b-6e04-493d-a363-2ebac1ea571f.png)

**Comment by pkudela** [comment]
Opraveno, uz by to melo byt v poradku viz. screenshot. Prosim otestujte.

![image](https://user-images.githubusercontent.com/16591052/145231777-5dbd9107-95af-437f-9ea3-9bc08cb80623.png)

![image](https://user-images.githubusercontent.com/16591052/145231879-2bad2b21-09d8-4832-9c4d-870a36615d75.png)

**Comment by kerschfilip** [comment]
opraveno, díky!
