### ISSUE TITLE
Admin - aj/čj

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/K5Journals#5]
Pro admin rozhraní bychom chtěli, aby bylo v angličtině nebo v češtině podle aktuálně vybraného jazyka.

Do dalšího komentáře vypíšu seznam anglických a českých tlačítek (tooltipů), které se mají zobrazovat.

**Comment by krizovj** [comment]
S editačním oknem také souvisí, že bychom tam potřebovali přidat funkci seznamů - odrážkový a číslovaný:
![seznamy](https://user-images.githubusercontent.com/21309201/65667126-5b401a80-e03f-11e9-8c38-85dd3fc4dcd5.jpg)

Tlačítka by měla být umístěna na liště po Kurzívě.

**Comment by krizovj** [comment]
Uvádím názvy tlačítek v češtině a angličtině. Jsou tam uvedeny také ty seznamy.
![admin](https://user-images.githubusercontent.com/21309201/65667161-6a26cd00-e03f-11e9-98db-c0edd407978f.jpg)

Uložit | Save
Zpět | Back
Opakovat / vpřed | Repeat
Formátování | Formats
Tučné | Bold
Kurzíva | Italic
Odrážkový seznam | Bulleted list
Číslovaný seznam | Numbered list
Zarovnat vlevo | Align left
Zarovnat na střed | Align center
Zarovnat vpravo | Align right
Zarovnat do bloku | Justify
Zrušit odsazení | Decrease indent
Odsadit text | Increase indent
Vložit odkaz | Insert / edit link
Vložit obrázek | Insert / edit image
Zdrojový kód | Source code
Nahrát PDF | Upload file

**Comment by krizovj** [comment]
Další seznamy, jde o položky v záložkách na liště
![formaty](https://user-images.githubusercontent.com/21309201/65667185-79a61600-e03f-11e9-8cb9-9bfd041f9f81.jpg)

Formátování | Formats
Nadpisy | Headline
Písmo | Inline
Odstavce | Paragraph
Zarovnání | Alignment

Nadpisy | Headline
Nadpis 1 | Headline 1
Nadpis 2 | Headline 2
Nadpis 3 | Headline 3
Nadpis 4 | Headline 4
Nadpis 5 | Headline 5
Nadpis 6 | Headline 6

Písmo | Inline
Tučné | Bold
Kurzíva | Italic
Podtržení | Underline
Přeškrtnutí | Strikethrough
Horní index | Superscript
Dolní index | Subscript
Zdrojový kód | Source code

Odstavce | Paragraph
Odstavec s mezerami | Paragraph
Citace | Quote
Oddíl | Div
Předformátovaný text | Pre

Zarovnání | Alignment
Vlevo | Left
Na střed | Center
Vpravo | Right
Do bloku | Justify

**Comment by krizovj** [comment]
Vložit odkaz - překlad
![odkaz](https://user-images.githubusercontent.com/21309201/65667226-92aec700-e03f-11e9-9515-c9e4547514ad.jpg)

Vložit odkaz | Insert / edit link
URL | URL
Zobrazený text | Text to display
Název | Title
Otevřít v novém okně / kartě? | Open in a new window? - Tady by mohlo být jen nějaké zaškrtávátko
Ano | Yes
Ne | No

**Comment by krizovj** [comment]
Nahrát obrázek
popsáno v issue https://github.com/ceskaexpedice/K5Journals/issues/3

**Comment by krizovj** [comment]
Nahrát PDF

Nahrát PDF | Upload file
Vybrat soubor | Browse for a file
Soubor nevybrán | No selected file
Nahrát soubor | Upload file

**Comment by krizovj** [comment]
Ohledně nahrávání souborů a obrázků mám dotaz, kolik se toho tam vlastně vejde? Předpokládám, že to je asi podle toho, kolik je místa na tom konkrétním serveru. Ale šlo by udělat nějakou lištu, která by ukazovala, kolik mám místa?
Nějak úplně jednoduše
![kolik](https://user-images.githubusercontent.com/21309201/65667373-e4efe800-e03f-11e9-809f-26f55de911e3.jpg)
<img width="319" alt="contextual-progress-bar" src="https://user-images.githubusercontent.com/21309201/65667384-eb7e5f80-e03f-11e9-8fd1-86fc00979952.png">

A s tím ještě souvisí možnost ten soubor zase smazat, což teď nemůžu udělat. Bylo by to možné?

**Comment by tumovam** [comment]
AJ verze (Admin webu) je ok. Issue by se dalo zavřít (já nemám oprávnění).

**Comment by kerschfilip** [comment]
k jaké tady došlo úpravě, prosím? Popisky v rámci textového editoru (TINY) jsou stále anglicky, myslím, že @krizovj a @tumovam šlo hlavně o jejich překlad.

Jinak ale myslím že tohle nespěchá a není to nutné řešit hned, díky

**Comment by albertoh** [comment]
Omyl, tady nic se nedelalo

**Comment by kerschfilip** [comment]
super, díky moc. Jen tahle ikona je stále nazvaná "Insert link to file" 
![image](https://user-images.githubusercontent.com/57805328/205960627-37cef511-eea9-4e7a-97ef-7c4a79248b4a.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Díky!
