### ISSUE TITLE
Nasazení nové verze - problém

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/K5Journals#52]
Ahoj,

pokusil jsem se nasadit poslední verzi aplikace, ale mám s tím problém.

Nejsem schopen se do aplikace přihlásit žádným účtem. Dle všeho nová instance aplikace ignoruje soubor `users.json` v domácím adresáři aplikace `~/.k5journals/`, tudíž nejsou k dispozici žádné účty používané v předchozí verzi.

Dle doporučení jsem nainstaloval poslední verzi Solr-u `8.11.1` a nainstaloval příslušné konfigurace dodané se zdrojovým kódem:
https://github.com/ceskaexpedice/K5Journals/archive/refs/tags/v2.1.tar.gz

Analýzou logu vidím, že nově jsou uživatelské účty zřejmě ukládány v Solr indexu, v jádře `users`:

![journals-00](https://user-images.githubusercontent.com/8750622/148643811-749da6f5-bc35-452d-81b4-9ac8df7bf09c.png)

Nicméně nově založené jádro `users` neobsahuje žádné, ani předdefinované, účty - proto se zřejmě nejsem schopen logicky přihlásit.

Pomocí curl-u jsem si tedy založil v jádře `users` pokusný admin účet:

![journals-01](https://user-images.githubusercontent.com/8750622/148644016-4872bf69-2740-4776-8f12-973188c4fc4e.png)

Nicméně ani s takto založeným účtem se nejsem schopen příhlásit:

![journals-02](https://user-images.githubusercontent.com/8750622/148644049-22029346-8545-4432-9413-1ecdacaceb99.png)

Otázky/připomínky

1. Jak validně založit/inicializovat uživatele? Lze použít stávající `users.json` soubor z předchozí instance? Pokud ano, jak?
2. Nová verze aplikace použije konfigurace všech časopisů z domovského adresáře `~/.k5journals/`? Opět mám pocit, že jsou ignorovány.
3. Stejně tak se po instalaci nové verze nenaplní ostatní jádra indexu. Musím jejich naplnění iniciovat ručně po přihlášení jako admin - viz bod 1. - nebo se to má sklidit z indexu Krameria automaticky na základě konfigurace z předchozí instance? Nebo musím nějak migrovat index?
4. Chybí cokoliv bližšího v dokumentaci/wiki ohledně upgradu aplikace na novou verzi - výsledkem je tudíž tato issue, protože tak trochu tápu :/
5. Heslo je v jádře `users` ukládáno v plaintextu nebo se musí nějak zahešovat?

Díky, MD

**Comment by albertoh** [comment]
Ahoj.
Mas pravdu, chybi popis ...
Reindexace bude nutna: nektere issue vyzadovaly zmeny v indexu, v konfiguraci, jak na konkretni cisla casopisu, tak i na celem nastaveni tech casopisy.

Nastaveni casopisu je v core "magazines". V administrace aplikace lze konfigurovat je.

Pro tuto verzi bylo pozadovano administraci uzivatelu. users.json uz neni pouzivan. Jak pises, to ted je v core users.
Hesla uzivatele jsou hashovana.
Lze pridat prvni admin uzivatel primo v admin rozhrani SOLRu, do core users:

{
        "name":"Administrator",
        "isAdmin":true,
        "username":"admin",
        "pwd":"-1278e91bc971a7f65f22c51c96ae968280b8bd4a7921445e",
}

To je uzivatel "admin", heslo: "test"
To heslo lze menit v administraci: "resetovat heslo" .

**Comment by mduda100871** [comment]
Ahoj,

tak už jsem schopen se přihlásit jako admin (s rolí administrátor - zaškrtnutý checkbox).

![asjournals-03](https://user-images.githubusercontent.com/8750622/148943879-e787de82-9c70-4b05-9eec-a9573a250293.png)

Přidal jsem tedy další uživatele (bez role administrátor), založil jsem časopisy a ty pak přiřadil příslušným uživatelům, příklad (uživatel "kvo"):

uživatel v admin rozhraní ->

![asjournals-00](https://user-images.githubusercontent.com/8750622/148942498-a4539982-0abe-42fc-b90e-d9bfea4632f1.png)

časopis v admin rozhraní ->

![asjournals-01](https://user-images.githubusercontent.com/8750622/148942516-b343cd0d-0186-49f5-afdd-19b5a211ddf9.png)

uživatel v solr-u ->

![asjournals-02](https://user-images.githubusercontent.com/8750622/148943152-c079adbf-7baf-4620-a1e4-12e029c1c363.png)

Problém ale je, že nejsem schopen se tímto neprivilegovaným uživatelem (bez admin role) přihlásit do aplikace. Ověřil jsem několikrát správnost jména i hesla. 

V okamžiku, kdy tomuto uživateli přiřadím zároveň i roli admina, tak jsem schopen se přihlásit, ale průšvih je, že pak se dostanu i na správu uživatelů a i správu ostatních časopisů, což je nežádoucí. Jakmile odeberu zpět roli admina, tak se opět nemohu přihlásit.

V čem může být problém?

Díky, MD

**Comment by albertoh** [comment]
Uzivatel se musi prihlasit jen na casopis, na ktery na pravo

**Comment by mduda100871** [comment]
OK, rozumím, v konkrétním kontextu se opravdu přihlásím.

Nicméně osobně mi to přijde hodně matoucí/zavádějící - asi by tam (na hlavní stránce aplikace) mělo být nějak zdůrazněno, že to je přihlášení jen pro globálního admina...nebo tak něco...alespoň v té bublinkové nápovědě...

MD

**Comment by kerschfilip** [comment]
Souhlasím, že to asi může být matoucí. Navrhuji to v nějaké další verzi doplnit tou zmíněnou nápovědou (viz #53)
