### ISSUE TITLE
Rubriku Recenzní řízení nahradit Lektorské řízení

### ISSUE THREAD

**Issue by zemanovav** [ceskaexpedice/K5Journals#55]
Bylo by, prosím, možné, přejmenovat u časopisu Česká literatura rubriku **Recenzní řízení** na **Lektorské řízení**? Přála by si to sama redakce časopisu především z důvodu, že označení Recenzní není přesné a nepoužívají ho. Děkuji.

**Comment by tumovam** [comment]
https://github.com/ceskaexpedice/K5Journals/issues/32

**Comment by zemanovav** [comment]
Změnu popisu rubriky Recenzní řízení na Lektorské řízení prosím udělat jak u časopisu Česká literatura, tak Cornova.
https://asjournals.lib.cas.cz/ceskaliteratura/pro-autory/recenzni-rizeni
https://asjournals.lib.cas.cz/cornova/pro-autory/recenzni-rizeni

**Comment by kerschfilip** [comment]
bude řešeno v rámci #32 . Názvy rubrik si budou moci nastavit administrátoři.
