### ISSUE TITLE
Špatný odkaz pod obálkou aktuálního čísla

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#70]
Obrázek obálky aktuálního čísla má fungovat jako odkaz zpět na hlavní stránku - pokud na něj ale kliknu na hlavní stránce, zmizí název časopisu v hlavičce a místo textu v pravé části stránky se objeví hláška "Text not found in..." Dále už funguje jen archiv a všechny textové stránky ukazují stejnou chybu o nenalezeném textu. Po Ctrl+F5 se objeví jen dva šedé pruhy a stránka se nenačte.

Problém je asi v tom, že po kliknutí na obálku aktuálního čísla z hlavní stránky se uživatel dostane do adresáře `/home/home`  místo je `/home`

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Díky, funguje. Opravu jsme si nasadili do produkce.
