### ISSUE TITLE
Vyhledávání Googlem

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#74]
Weby časopisů se téměř neukazují ve výsledcích vyhledávání Googlu, Seznamu a dalších. Důvodem je asi fakt, že aplikace je udělaná jako single page app a ke spuštění potřeba javascript, bez něj je vidět jen prázdná stránka - tu taky většina vyhledávačů apod. vidí, protože javascript nespouští.

**Comment by albertoh** [comment]
Pro spravne fungovani bude nutne instalovat na serveru nodejs

**Comment by albertoh** [comment]
Test na 
https://k7journals.inovatika.dev/

Je nutne mit nainstalovan nodejs. Aplikace ted je servirovana z portu 4000 (port pro nodejs). Apache presmeruje tam.
Zaroven tomcat bezi jako driv, v portu 8080, jako API pro nodejs proces.

Do hlavicky stranky pridavaji se meta tagy "description", "author" a "keywords", prevzaty z konfigurace casopisu

![image](https://user-images.githubusercontent.com/5946836/203924805-62667425-0feb-45ab-b482-3ecc1f3c0071.png)

![image](https://user-images.githubusercontent.com/5946836/203925154-684c9b85-23eb-4e58-a867-a8bbc30776f9.png)
