### ISSUE TITLE
Překládání názvů článků do angličtiny/češtiny

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#75]
Při přepnutí verze webu do anglické mutace se zobrazují anglické názvy článků (je-li anglický překlad uveden v metadatech).

Tato vlastnost by měla být konfigurovatelná na úrovni časopisu (některé ústavy si přejí nechat názvy článků v češtině i pokud si uživatel prohlíží anglickou verzi webu)

**Comment by albertoh** [comment]
![image](https://user-images.githubusercontent.com/5946836/203505635-91907e1a-d631-43dd-b353-b478fe8aa99e.png)

![image](https://user-images.githubusercontent.com/5946836/203505811-a33eb623-3b02-4efc-bd35-4d8ba47efc14.png)

**Comment by kerschfilip** [comment]
Funguje, díky!
