### ISSUE TITLE
Úprava UI při prohlížení PDF

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#77]
Současná podoba UI při prohlížení článků nechává hodně prostoru lištám a na samotný obsah je místa poměrně málo:
![image](https://user-images.githubusercontent.com/57805328/196423477-8b75bc25-2871-4fde-ae07-3a95ed5d5e78.png)

Lepším řešením by mohlo být, že se stránka “natáhne” alespoň na délku jedné A4 a nebude působit tak stísněně. Po úpravě například takto:
![image](https://user-images.githubusercontent.com/57805328/196423659-3c73444d-7348-419c-bac4-bc61271fa276.png)

**Comment by pkudela** [comment]
@kerschfilip dobry den, mate na mysli, ze by se v pripade prohlizecky nezobrazovala paticka? Take jsem chtel poznamenat, ze celkove ja design stranek pro tyto ucely znacne komplikovany a neohebny, ten design navrhoval myslim nekdo od vas, je to ale jiz delsi dobu. Nezvazujete nekdy v budoucnu redesign teto aplikace? S tim by se svezl i navrh noveho flexibilnejsiho layoutu.

**Comment by kerschfilip** [comment]
dobrý den, @pkudela, na screenshotu jsem to neukázal dobře. Jestli to chápu správně, tak aplikace zobrazuje obsah rozdělený v podstatě do 3 částí - header, main a footer. Myslel jsem to tak, že při prohlížení PDF by nebyla část s hlavním obsahem omezena na výšku 500 px jako je to teď, ale natáhla by se na velikost A4 (cca 900 px?). Patička by stále byla na místě, ale níž. Celá stránka by pak vlastně byla delší, ale podle mě by se na ni lépe koukalo: 
![image](https://user-images.githubusercontent.com/57805328/205146316-dd202acf-4913-4088-a0b7-b75f943ff959.png)

Chápu, že design není v tuhle chvíli napsaný tak, aby se dobře uzpůsoboval podobným nápadům, pokud to nepůjde, tak se nedá nic dělat. Myslím, že KNAV navrhovala spíš funkčnost, než samotnou podobu aplikace a způsob, jak je napsaná, ale to je jedno :-) Souhlasím, že zamyslet se výhledově nad redesignem by nebylo špatné.

**Comment by pkudela** [comment]
Dobry den, musite chapat, ze velikost A4 na wbu neexistuje, nyni je design a layout koncipovan tak, ze header a footer jsou fixni a obsahova cast mezi nima se prizpusobuje aktualni velikosti prohlizece viz. screenshoty nize. Mohu udelat to, ze pro ctecku zvetsim natvrdo vysku obsahove casti na cca rozmer A4, ale bude to mit za nasledek to, ze se objevi 2 vertikalni scrollbary jeden pro danou stranku a druhy pro cely prohlizec viz. screenshot nize, chcete to tak udelat?

Screenshoty soucasneho chovani, kdy se prizpusobuje obsahova cast vysce prohlizece:
![image](https://user-images.githubusercontent.com/16591052/205270153-b5daa121-1754-4335-9d1f-0e04107f56ab.png)

![image](https://user-images.githubusercontent.com/16591052/205270254-bdc14855-13ed-4dec-9cd4-d6838b9d6f69.png)

Po uprave vysky, nekde se scollbar pro stranu neobjevi, nekde ano, pak budou scrollbary 2:
![image](https://user-images.githubusercontent.com/16591052/205270594-2520f098-14e4-46cf-b501-3249429d680b.png)

![image](https://user-images.githubusercontent.com/16591052/205270706-d2e0e1f1-e2af-400a-a281-1aae77e63f74.png)

**Comment by pkudela** [comment]
@kerschfilip je to nasazene na serveru -> https://k7journals.inovatika.dev/knihyadejiny/article/uuid:620e41c7-9496-4986-902f-fdd5f95fdde6
Prosim otestujte, jestli Vam to takto vyhovuje.

**Comment by kerschfilip** [comment]
@pkudela jasně, že A4 na webu neexistuje, ale jde to udělat tak, že z ní bude vidět víc... Myslel jsem to přesně tak, jak jste to udělal, ale musím uznat, že to není moc uživatelsky přívětivé. Na těch vašich screenshotech to ještě vypadá relativně dobře, ale třeba [tady](https://k7journals.inovatika.dev/knihyadejiny/article/uuid:94efbf2f-6662-4fc3-ad07-195b2a93e532) se mi tvoří už scrollbary tři - jeden na obsah čísla, jeden na PDF a jeden na celou stránku, a to už je teda dost nepřehledné.

Vraťte to, prosím, do původního stavu a úpravu UI necháme až na nějaký větší redesign. Moc díky!

**Comment by pkudela** [comment]
@kerschfilip hotovo, nasazeno na serveru

**Comment by kerschfilip** [comment]
Díky!
