### ISSUE TITLE
Chyba při generování citace

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/K5Journals#8]
V naší testovací verzi (tady: https://asjournals-test.lib.cas.cz/knihyadejiny/home) nefunguje generování citací. 
Nevím, jestli je problém při instalaci, jestli se nemusí něco nastavovat nebo jestli to není chyba... 

Vypadá to takhle:
![citace](https://user-images.githubusercontent.com/21309201/67490536-ad428300-f673-11e9-9978-0d4f65503ff6.jpg)

**Comment by albertoh** [comment]
Vypada na problem na serveru kde se generuje citace:

http://citace.rychtar.cloud/v1/kramerius?format=html&url=https://kramerius.lib.cas.cz&uuid=uuid:08548a9c-ad4a-413e-821a-4d52cb8e65de

@honza-rychtar, muzes se podivat? Bezi?

**Comment by krizovj** [comment]
mně to tedy v Krameriovi jde, jestli vám ta informace pomůže (je to ten stejný článek):
![citacek](https://user-images.githubusercontent.com/21309201/67547026-36060100-f6fe-11e9-8335-c917161fa320.jpg)

**Comment by albertoh** [comment]
Mam odpoved od Honzy.
Server ted bezi tady:

https://citace.kramerius.cloud/v1/kramerius

Je nutne v config.json (~/.k5journals/config.json), v sekce server nastavit ho tak:

"citation_server", "http://citace.kramerius.cloud/v1/kramerius?format=html&url=https://kramerius.lib.cas.cz&uuid="

**Comment by krizovj** [comment]
Je možné to přihodit do dokumentace prosím?

**Comment by mduda100871** [comment]
Drobná oprava:

místo `"citation_server", ` má být `"citation_server": `, příklad:

![citace-01](https://user-images.githubusercontent.com/8750622/67928842-4b76a180-fbbc-11e9-80e4-6d6c1523ded5.png)


MD

**Comment by kerschfilip** [comment]
v současné verzi generování citací funguje, issue zavírám
