### ISSUE TITLE
Nefunkční odkazy na úvodním webu

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#80]
Zdravím,

všiml jsem si ještě chyb na úvodním webu https://asjournals-test.lib.cas.cz/magazines/casopisy, kde nefungují některé odkazy:
- Seznam časopisů se nedá řadit (od A-Z/Z-A)
- odkazy na kartách jednotlivých časopisů nefungují (Oblast, ISSN, Klíčová slova, Přístup)

protože mi to připadá jako docela závažná chyba, přidávám to ještě k aktuálnímu rozvoji, díky.

**Comment by albertoh** [comment]
Hotovo

**Comment by kerschfilip** [comment]
Díky!
