### ISSUE TITLE
Správa uživatelů - překlep

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/K5Journals#87]
prosím o opravu překlepu v administraci aplikace - správně to má být "Správa uživatelů", díky :-)
![image](https://user-images.githubusercontent.com/57805328/205963728-97e67b99-7c40-45b0-948b-ec46649ca976.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Díky!

**Comment by albertoh** [comment]
Opraveno

**Comment by kerschfilip** [comment]
Děkuji!
